services:
  backend:
    build: backend
    restart: always
    ports:
      - 3001:3001
  frontend:
    build: frontend
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - backend